### ISSUE TITLE
[Feat] 슬랙 메시지 API

### ISSUE THREAD

**Issue by Griotold** [Logistics-system-project/Notification-service#2]
## Description
> 설명
- 슬랙 메시지 생성
- 슬랙 메시지 목록 조회
- 슬랙 메시지 상세 조회

## Requirements
> 기능 구현을 위한 요구사항
- [ ]  슬랙 메시지를 저장하는 엔티티를 생성합니다. 필수 정보는 다음과 같습니다.
    - 수신 ID, 메시지, 발송 시간등
- [ ]  슬랙 앱을 생성하고 API를 통해 메시지 발송 기능을 구현합니다.
- [ ]  권한 관리는 아래와 같습니다.
    - 로그인한 모든 사용자 및 내부 시스템은 발송 가능
![image](https://github.com/user-attachments/assets/90c61354-523c-4938-8624-251c5db518eb)

## Estimated Duration
12/14(토) ~ 12/15 (일) [2일]

## Todo
> 기능 구현을 위한 할 일 작성
- [ ] 슬랙 메시지 생성
- [ ] 슬랙 메시지 목록 조회
- [ ] 슬랙 메시지 상세 조회
